#!/bin/bash

# Stop process if some command fails.
set -e

# Extracting parameters.
VERSION_TYPE=${1}

# Version increase type validation.
if [[ "$VERSION_TYPE" != "patch" && "$VERSION_TYPE" != "minor" && "$VERSION_TYPE" != "major" ]]; then
  echo "Error: Invalid version increase type, expected values: [patch, minor, major]"
  exit 1
fi

# Branch to manage.
BRANCH_DEST="master"
BRANCH_SOURCE="$(git rev-parse --abbrev-ref HEAD)"

# 1. Increase Project version
echo "Increasing project version ..."
NEW_VERSION=$(npm version $VERSION_TYPE --no-git-tag-version)

# Commit and PR informations.
COMMIT_MSG="Deploying project version $NEW_VERSION via Shell"
PR_TITLE="PR for version $NEW_VERSION from $BRANCH_SOURCE to $BRANCH_DEST"
PR_BODY="Pull request for version $NEW_VERSION automatically generated by sh script"

# 2. Build project
echo "Building project ..."
NODE_ENV=production npm run build

# 3. Git Commit and Push
echo "Committing e pushing ..."
git add .
git commit -m "$COMMIT_MSG" || echo "No change to commit"
git push origin "$BRANCH_SOURCE"

# 4. Pull Request (via GitHub CLI)
echo "Creating pull request to $BRANCH_DEST ..."
gh pr create --base "$BRANCH_DEST" --head "$BRANCH_SOURCE" --title "$PR_TITLE" --body "$PR_BODY"

# 5. End Script
echo "Deploy completed successfully"