#!/bin/bash

# stop process if some command fails
set -e  

# === CONFIG ===
BRANCH_DEST="master"
BRANCH_SOURCE="$(git rev-parse --abbrev-ref HEAD)"
COMMIT_MSG="Deploying project via sh"
PR_TITLE="PR via sh from $BRANCH_SOURCE to $BRANCH_DEST"
PR_BODY="Pull request automatically generated by sh script"

# === 1. BUILD ===
echo "🏗️ Building project ..."
NODE_ENV=production npm run build

# === 2. GIT COMMIT & PUSH ===
echo "📦 Committing e pushing ..."
git add .
git commit -m "$COMMIT_MSG" || echo "No change to commit"
git push origin "$BRANCH_SOURCE"

# === 3. PULL REQUEST (via GitHub CLI) ===
echo "🚀 Creating pull request to $BRANCH_DEST ..."
gh pr create --base "$BRANCH_DEST" --head "$BRANCH_SOURCE" --title "$PR_TITLE" --body "$PR_BODY"

# === 4. End Script ===
echo "✅ Done"