#!/bin/bash

# Stop process if some command fails.
set -e

# Extracting parameters.
VERSION_TYPE=${1}

# Version increase type validation.
if [[ "$VERSION_TYPE" != "patch" && "$VERSION_TYPE" != "minor" && "$VERSION_TYPE" != "major" ]]; then
  echo "Error: Invalid version increase type, expected values: [patch, minor, major]"
  exit 1
fi

# Configuration
BRANCH_DEST="master"
BRANCH_SOURCE="$(git rev-parse --abbrev-ref HEAD)"
COMMIT_MSG="Deploying project via sh"
PR_TITLE="PR via sh from $BRANCH_SOURCE to $BRANCH_DEST"
PR_BODY="Pull request automatically generated by sh script"

# 1. Build project
echo "Building project ..."
NODE_ENV=production npm run build

# 2. Git Commit and Push
echo "Committing e pushing ..."
git add .
git commit -m "$COMMIT_MSG" || echo "No change to commit"
git push origin "$BRANCH_SOURCE"

# 3. Pull Request (via GitHub CLI)
echo "Creating pull request to $BRANCH_DEST ..."
gh pr create --base "$BRANCH_DEST" --head "$BRANCH_SOURCE" --title "$PR_TITLE" --body "$PR_BODY"

# 4. Increase Project version

# 5. End Script
echo "Deploy completed successfully"